use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

use crate::config::MonitorScopeSettings;

/// Unique agent identity assigned during enrollment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentIdentity {
    pub id: String,
    pub hostname: String,
    pub platform: String,
    pub version: String,
    pub enrolled_at: String,
    pub last_seen: String,
    pub status: AgentStatus,
    pub labels: HashMap<String, String>,
    #[serde(default)]
    pub health: AgentHealth,
    /// Per-agent monitoring scope override. When `None`, the server-global scope applies.
    #[serde(default)]
    pub monitor_scope: Option<MonitorScopeSettings>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AgentHealth {
    #[serde(default)]
    pub pending_alerts: usize,
    #[serde(default)]
    pub telemetry_queue_depth: usize,
    #[serde(default)]
    pub update_state: Option<String>,
    #[serde(default)]
    pub update_target_version: Option<String>,
    #[serde(default)]
    pub last_update_error: Option<String>,
    #[serde(default)]
    pub last_update_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AgentStatus {
    Online,
    Stale,
    Offline,
    Deregistered,
}

/// A one-time enrollment token generated by the server.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentToken {
    pub token: String,
    pub created_at: String,
    pub uses_remaining: u32,
    pub max_uses: u32,
    /// Optional expiration timestamp (RFC 3339). `None` means no expiry.
    #[serde(default)]
    pub expires_at: Option<String>,
}

impl EnrollmentToken {
    pub fn new(max_uses: u32) -> Self {
        use rand::RngCore;
        let mut bytes = [0u8; 16];
        rand::rngs::OsRng.fill_bytes(&mut bytes);
        Self {
            token: hex::encode(bytes),
            created_at: chrono::Utc::now().to_rfc3339(),
            uses_remaining: max_uses,
            max_uses,
            expires_at: None,
        }
    }

    /// Create a token with a TTL in seconds.
    pub fn new_with_ttl(max_uses: u32, ttl_secs: u64) -> Self {
        let mut token = Self::new(max_uses);
        let expires = chrono::Utc::now() + chrono::Duration::seconds(ttl_secs as i64);
        token.expires_at = Some(expires.to_rfc3339());
        token
    }

    pub fn is_valid(&self) -> bool {
        if self.uses_remaining == 0 {
            return false;
        }
        if let Some(ref exp) = self.expires_at {
            match chrono::DateTime::parse_from_rfc3339(exp) {
                Ok(dt) => return chrono::Utc::now() < dt,
                Err(_) => return false, // malformed timestamp → treat as expired
            }
        }
        true
    }

    pub fn consume(&mut self) -> bool {
        if self.uses_remaining > 0 {
            self.uses_remaining -= 1;
            true
        } else {
            false
        }
    }
}

/// Enrollment request sent by an agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollRequest {
    pub enrollment_token: String,
    pub hostname: String,
    pub platform: String,
    pub version: String,
    pub labels: Option<HashMap<String, String>>,
}

/// Enrollment response returned by the server.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollResponse {
    pub agent_id: String,
    pub server_version: String,
    pub heartbeat_interval_secs: u64,
    pub policy_poll_interval_secs: u64,
}

/// Server-side agent registry backed by a JSON file.
pub struct AgentRegistry {
    agents: HashMap<String, AgentIdentity>,
    tokens: Vec<EnrollmentToken>,
    store_path: String,
    heartbeat_interval: u64,
    staleness_multiplier: u64,
}

impl AgentRegistry {
    pub fn new(store_path: &str) -> Self {
        let mut reg = Self {
            agents: HashMap::new(),
            tokens: Vec::new(),
            store_path: store_path.to_string(),
            heartbeat_interval: 30,
            staleness_multiplier: 3,
        };
        reg.load();
        reg
    }

    pub fn heartbeat_interval(&self) -> u64 {
        self.heartbeat_interval
    }

    /// Create a new enrollment token.
    pub fn create_token(&mut self, max_uses: u32) -> EnrollmentToken {
        let token = EnrollmentToken::new(max_uses);
        self.tokens.push(token.clone());
        self.save();
        token
    }

    /// Create a new enrollment token with a TTL.
    pub fn create_token_with_ttl(&mut self, max_uses: u32, ttl_secs: u64) -> EnrollmentToken {
        let token = EnrollmentToken::new_with_ttl(max_uses, ttl_secs);
        self.tokens.push(token.clone());
        self.save();
        token
    }

    /// Enroll a new agent.
    pub fn enroll(&mut self, req: &EnrollRequest) -> Result<EnrollResponse, String> {
        // Validate token
        let token_entry = self
            .tokens
            .iter_mut()
            .find(|t| t.token == req.enrollment_token && t.is_valid());
        match token_entry {
            Some(t) => {
                t.consume();
            }
            None => return Err("invalid or expired enrollment token".into()),
        }

        let agent_id = generate_agent_id();
        let now = chrono::Utc::now().to_rfc3339();

        let identity = AgentIdentity {
            id: agent_id.clone(),
            hostname: req.hostname.clone(),
            platform: req.platform.clone(),
            version: req.version.clone(),
            enrolled_at: now.clone(),
            last_seen: now,
            status: AgentStatus::Online,
            labels: req.labels.clone().unwrap_or_default(),
            health: AgentHealth::default(),
            monitor_scope: None,
        };

        self.agents.insert(agent_id.clone(), identity);
        self.save();

        Ok(EnrollResponse {
            agent_id,
            server_version: env!("CARGO_PKG_VERSION").to_string(),
            heartbeat_interval_secs: self.heartbeat_interval,
            policy_poll_interval_secs: 60,
        })
    }

    /// Process a heartbeat from an agent.
    pub fn heartbeat(
        &mut self,
        agent_id: &str,
        version: &str,
        health: Option<AgentHealth>,
    ) -> Result<(), String> {
        let agent = self
            .agents
            .get_mut(agent_id)
            .ok_or_else(|| "unknown agent".to_string())?;
        agent.last_seen = chrono::Utc::now().to_rfc3339();
        agent.version = version.to_string();
        agent.status = AgentStatus::Online;
        if let Some(health) = health {
            agent.health = health;
        }
        self.save();
        Ok(())
    }

    /// Deregister an agent.
    pub fn deregister(&mut self, agent_id: &str) -> Result<(), String> {
        let agent = self
            .agents
            .get_mut(agent_id)
            .ok_or_else(|| "unknown agent".to_string())?;
        agent.status = AgentStatus::Deregistered;
        self.save();
        Ok(())
    }

    /// Get a single agent by ID.
    pub fn get(&self, agent_id: &str) -> Option<&AgentIdentity> {
        self.agents.get(agent_id)
    }

    /// List all registered agents.
    pub fn list(&self) -> Vec<&AgentIdentity> {
        self.agents.values().collect()
    }

    /// Count agents by status.
    pub fn counts(&self) -> HashMap<String, usize> {
        let mut counts = HashMap::new();
        for agent in self.agents.values() {
            let key = serde_json::to_string(&agent.status)
                .unwrap_or_else(|_| "unknown".into())
                .trim_matches('"')
                .to_string();
            *counts.entry(key).or_insert(0) += 1;
        }
        counts
    }

    /// Update staleness for agents that haven't heartbeated recently.
    pub fn refresh_staleness(&mut self) {
        let threshold_secs = self.heartbeat_interval * self.staleness_multiplier;
        let now = chrono::Utc::now();
        for agent in self.agents.values_mut() {
            if agent.status == AgentStatus::Deregistered {
                continue;
            }
            if let Ok(last) = chrono::DateTime::parse_from_rfc3339(&agent.last_seen) {
                let elapsed = (now - last.with_timezone(&chrono::Utc)).num_seconds();
                if elapsed > threshold_secs as i64 {
                    agent.status = AgentStatus::Stale;
                } else {
                    agent.status = AgentStatus::Online;
                }
            }
        }
    }

    /// List active enrollment tokens.
    pub fn list_tokens(&self) -> &[EnrollmentToken] {
        &self.tokens
    }

    /// Set the monitoring scope override for a specific agent.
    pub fn set_monitor_scope(
        &mut self,
        agent_id: &str,
        scope: Option<MonitorScopeSettings>,
    ) -> Result<(), String> {
        let agent = self
            .agents
            .get_mut(agent_id)
            .ok_or_else(|| "unknown agent".to_string())?;
        agent.monitor_scope = scope;
        self.save();
        Ok(())
    }

    /// Get the monitoring scope for a specific agent (returns the override or None).
    pub fn get_monitor_scope(&self, agent_id: &str) -> Option<&MonitorScopeSettings> {
        self.agents
            .get(agent_id)
            .and_then(|a| a.monitor_scope.as_ref())
    }

    fn save(&self) {
        let data = RegistryData {
            agents: self.agents.clone(),
            tokens: self.tokens.clone(),
        };
        if let Ok(json) = serde_json::to_string_pretty(&data) {
            let path = Path::new(&self.store_path);
            if let Some(parent) = path.parent() {
                let _ = fs::create_dir_all(parent);
            }
            let tmp = format!("{}.tmp", self.store_path);
            if fs::write(&tmp, &json).is_ok() {
                let _ = fs::rename(&tmp, path);
            }
        }
    }

    fn load(&mut self) {
        let path = Path::new(&self.store_path);
        if let Ok(raw) = fs::read_to_string(path)
            && let Ok(data) = serde_json::from_str::<RegistryData>(&raw)
        {
            self.agents = data.agents;
            self.tokens = data.tokens;
        }
    }
}

#[derive(Serialize, Deserialize)]
struct RegistryData {
    agents: HashMap<String, AgentIdentity>,
    tokens: Vec<EnrollmentToken>,
}

fn generate_agent_id() -> String {
    use rand::Rng;
    let mut rng = rand::thread_rng();
    let bytes: Vec<u8> = (0..8).map(|_| rng.r#gen()).collect();
    format!("agent-{}", hex::encode(bytes))
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enrollment_token_lifecycle() {
        let mut token = EnrollmentToken::new(2);
        assert!(token.is_valid());
        assert!(token.consume());
        assert!(token.is_valid());
        assert!(token.consume());
        assert!(!token.is_valid());
        assert!(!token.consume());
    }

    #[test]
    fn registry_enroll_and_heartbeat() {
        let dir = std::env::temp_dir().join("wardex_test_enrollment");
        let _ = fs::create_dir_all(&dir);
        let store = dir.join("agents.json");
        let _ = fs::remove_file(&store);

        let mut reg = AgentRegistry::new(store.to_str().unwrap());
        let token = reg.create_token(5);

        let req = EnrollRequest {
            enrollment_token: token.token.clone(),
            hostname: "test-host".into(),
            platform: "linux".into(),
            version: "0.15.0".into(),
            labels: None,
        };

        let resp = reg.enroll(&req).expect("enroll should succeed");
        assert!(resp.agent_id.starts_with("agent-"));
        assert_eq!(resp.heartbeat_interval_secs, 30);

        // Heartbeat
        reg.heartbeat(&resp.agent_id, "0.15.0", None)
            .expect("heartbeat should succeed");

        // List
        let agents = reg.list();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].hostname, "test-host");

        // Deregister
        reg.deregister(&resp.agent_id)
            .expect("deregister should succeed");
        assert_eq!(
            reg.get(&resp.agent_id).unwrap().status,
            AgentStatus::Deregistered
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn invalid_token_rejected() {
        let dir = std::env::temp_dir().join("wardex_test_enrollment_bad");
        let _ = fs::create_dir_all(&dir);
        let store = dir.join("agents.json");
        let _ = fs::remove_file(&store);

        let mut reg = AgentRegistry::new(store.to_str().unwrap());

        let req = EnrollRequest {
            enrollment_token: "bad-token".into(),
            hostname: "test-host".into(),
            platform: "linux".into(),
            version: "0.15.0".into(),
            labels: None,
        };

        let result = reg.enroll(&req);
        assert!(result.is_err());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn staleness_detection() {
        let dir = std::env::temp_dir().join("wardex_test_staleness");
        let _ = fs::create_dir_all(&dir);
        let store = dir.join("agents.json");
        let _ = fs::remove_file(&store);

        let mut reg = AgentRegistry::new(store.to_str().unwrap());
        let token = reg.create_token(1);

        let req = EnrollRequest {
            enrollment_token: token.token.clone(),
            hostname: "stale-host".into(),
            platform: "macos".into(),
            version: "0.15.0".into(),
            labels: None,
        };
        let resp = reg.enroll(&req).unwrap();

        // Manually backdate the last_seen
        if let Some(agent) = reg.agents.get_mut(&resp.agent_id) {
            let old = chrono::Utc::now() - chrono::Duration::seconds(300);
            agent.last_seen = old.to_rfc3339();
        }

        reg.refresh_staleness();
        assert_eq!(reg.get(&resp.agent_id).unwrap().status, AgentStatus::Stale);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn counts_by_status() {
        let dir = std::env::temp_dir().join("wardex_test_counts");
        let _ = fs::create_dir_all(&dir);
        let store = dir.join("agents.json");
        let _ = fs::remove_file(&store);

        let mut reg = AgentRegistry::new(store.to_str().unwrap());
        let token = reg.create_token(3);

        for host in &["a", "b", "c"] {
            let req = EnrollRequest {
                enrollment_token: token.token.clone(),
                hostname: host.to_string(),
                platform: "linux".into(),
                version: "0.15.0".into(),
                labels: None,
            };
            reg.enroll(&req).unwrap();
        }

        let counts = reg.counts();
        assert_eq!(*counts.get("online").unwrap_or(&0), 3);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn token_ttl_valid() {
        let token = EnrollmentToken::new_with_ttl(5, 3600);
        assert!(token.is_valid());
        assert!(token.expires_at.is_some());
    }

    #[test]
    fn token_ttl_expired() {
        let mut token = EnrollmentToken::new_with_ttl(5, 1);
        // Force expiration to the past
        let past = chrono::Utc::now() - chrono::Duration::seconds(10);
        token.expires_at = Some(past.to_rfc3339());
        assert!(!token.is_valid());
    }

    #[test]
    fn token_no_ttl_valid() {
        let token = EnrollmentToken::new(3);
        assert!(token.is_valid());
        assert!(token.expires_at.is_none());
    }

    #[test]
    fn token_serialize_round_trip() {
        let token = EnrollmentToken::new_with_ttl(2, 600);
        let json = serde_json::to_string(&token).unwrap();
        let restored: EnrollmentToken = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.expires_at, token.expires_at);
        assert_eq!(restored.max_uses, 2);
    }
}
