apiVersion: v1
kind: Service
metadata:
  name: wardex
  labels:
    app.kubernetes.io/name: wardex
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9077
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: wardex
